README.md

Adding MadHacks

---

README.md

Add HackUCI

---

README.md

Thanks for making this calendar!

Adding Hack BU to README.md.

---

README.md

Add HackMIT 2015

---

README.md

MLH is gonna have fun dealing with this one.. #HackMIT

Adding Hack the North 2015

---

README.md

Added Kent Hack Enough to the weekend of 10.9 - 10.11.

added Kent Hack Enough

---

README.md

Added ecomhack 2015

---

README.md

Hello, I really like this repo and would like to help you updating it.
This PR is to add the AngelHack that will happen in Amsterdam next July

Add AngelHack Amsterdam 7.4 - 7.5

---

README.md

Added dates and link for AngelHack Cairo.

AngelHack Cairo Announced

---

README.md

Thanks to @itsbilal for the heads up!

Added Waterloo Tech Retreat, Website and Date Details

---

README.md

Confirmed location for AngelHack Silicon Valley:  Palo Alto, CA
http://www.eventbrite.com/e/angelhack-silicon-valley-2015-tickets-15776829923

Confirmed location for AngelHack Silicon Valley

---

README.md

New hackathon in Toronto

---

README.md

My first pull request! :smile:

Added Amazon AWS re:invent Hackathon)

---

README.md

Added the Montreal MasterCard Hackathon Competition

Added MasterCard Master of Code Montreal

---

README.md

Add HackDartmouth

---

README.md

Monthly Music Hackathon
Genesys Hackathon

Added two Toronto hackathons

---

README.md

Please add my upcoming hackathon to your calendar.  Thanks!

Added GSA Digital Innovation Hackathon

---

README.md

Previous pull request closed due to violation of maintaining alphabetical sorting.

Add four hackathons

---

README.md

added london hackathon with link (more details to be determined)

added upcoming hackathon (london hackathon, dec 15)

---

README.md

Added ecommerce focussed hackathons 
Cities
- Cologne, Germany
- Berlin, Germany
- New York, NY

Added ecomhack Hackathons

---

README.md

Added  [Hack the Debate](http://hackthedebate.com/) | Washington, DC | 11.7 - 11.8 |

Added Hack the Debate

---

README.md

Quickbooks Connect Hackathon
Sunday, Nov 01 2015 02:00 AM PST
San Jose, CA
http://www.hackathon.io/quickbooks-connect

quickbooks hackathon added

---

README.md

added HackPrinceton, Codestellation; updated HackNJIT

updated several upcomming hackathon

---

Past-Hackathons.md

Added a hackathon

---

Past-Hackathons.md
README.md

Simply updated the list. Moved everything from this weekend to the past hackathons list.

Moved past hackathons away from Upcoming to Past Hackathons

---

README.md

Open hack hackathon added 
http://www.openhack.io

New Hackathon added

---

README.md

added Los Altos Hacks hackathon, happening in mountain view, CA on Jan 30

Added Los Altos Hacks

---

README.md

add [HackTbilisi](2015f.hacktbilisi.com/en)

added HackTbilisi

---

README.md

Added HackYSU

---

README.md

I would like to add the hackathon I help advise to this calendar, PantherHacks in Milwaukee, Wisconsin. Our website is under construction but it will be finished very soon.

Adding PantherHacks

---

README.md

Source for MLH events: https://mlh.io/seasons/s2016/events

Added SpartaHack and MLH events from website

---

README.md

Added Healthcare Hackathon (1.22-1.24) and Hack the Brain in New Haven, CT for next semester

Add 2 New Haven, CT Hackathons

---

README.md

Change HackBeanpot's URL to the website, not the Eventbrite

---

README.md

Add MakeMIT Hardware Hackathon for February 2016

Add MakeMIT

---

README.md

SotonHack
February 5-7, 
Southampton, UK
http://hacka.typeform.com/to/t5o4r5
Thanks!

Add SotonHack

---

README.md

Added Scotiabank Hackathon

---

README.md

Registration is still open but closing soon!

Added MangoHacks

---

README.md

Add [VTHacks](http://www.vthacks.com/) 2.26 to 2.28 in Blacksburg, VA

Added VTHacks

---

README.md

The Open Source Track is a month-long initiative to encourage people to Open Source projects, whether by fixing bugs, creating new features, or updating and writing documentation.

IndiaHacks Open source

---

README.md

Added Qredo Hackathon

---

README.md

Added HackFest ISM, Dhanbad, India 3.4 -3.6
[http://www.hackfestism.org/](http://www.hackfestism.org/)

Added HackFest ISM

---

Past-Hackathons.md
README.md

- Added Header row to Past Hackathons. (So 2016 past hackathons is in a real table.)
- Added HackGSU, Brandeis Makeathon, and Bitcamp to Upcoming Hackathons. 
- Roll over Past Hackathons.

Added many hackathons from Issue Backlog, among other cleaning tasks.

---

README.md

Uncommon Hacks, Chicago, IL, 4/16-4/17

Add Uncommon Hacks (2016)

---

README.md

I made some unneeded syntax changes (because I'm avoiding studying).
Feel free to cherry-pick any/no commits! :smile:

Unnecessary syntax changes
